import {
	Alert02Icon,
	AlertCircleIcon,
	ArrowDown01Icon,
	ArrowLeft01Icon,
	ArrowRight01Icon,
	ArrowUp01Icon,
	BlueskyIcon,
	CheckmarkCircle01Icon,
	CodeIcon,
	Copy01Icon,
	DiscordIcon,
	Download01Icon,
	Edit02Icon,
	ExternalLinkIcon,
	File01Icon,
	Folder01Icon,
	GithubIcon,
  HeartIcon,
	InfoIcon,
	InstagramIcon,
	LightbulbIcon,
	LinkedinIcon,
	ListViewIcon,
	MinusSignIcon,
	PackageIcon,
	PencilEdit02Icon,
	PlusSignIcon,
	QuestionIcon,
	RedditIcon,
	ReloadIcon,
	Rocket01Icon,
	Search01Icon,
	ServerStackIcon,
	StarIcon,
	TerminalIcon,
	Tick02Icon,
	TrashIcon,
	TwitchIcon,
	Upload01Icon,
	NewTwitterIcon,
	XIcon,
	YoutubeIcon
} from '@hugeicons/core-free-icons';

export const iconDefinitions = {
	info: InfoIcon,
	warning: Alert02Icon,
	danger: AlertCircleIcon,
	check: Tick02Icon,
	x: XIcon,
	plus: PlusSignIcon,
	minus: MinusSignIcon,
	question: QuestionIcon,
	lightbulb: LightbulbIcon,
	rocket: Rocket01Icon,
	star: StarIcon,
	heart: HeartIcon,
	menu: ListViewIcon,
	'chevron-left': ArrowLeft01Icon,
	'chevron-right': ArrowRight01Icon,
	'arrow-up': ArrowUp01Icon,
	'arrow-down': ArrowDown01Icon,
	'external-link': ExternalLinkIcon,
	search: Search01Icon,
	copy: Copy01Icon,
	download: Download01Icon,
	upload: Upload01Icon,
	edit: PencilEdit02Icon,
	trash: TrashIcon,
	refresh: ReloadIcon,
	code: CodeIcon,
	terminal: TerminalIcon,
	git: GithubIcon,
	package: PackageIcon,
	server: ServerStackIcon,
	file: File01Icon,
	folder: Folder01Icon,

	'brand-github': GithubIcon,
	'brand-x': NewTwitterIcon,
	'brand-discord': DiscordIcon,
	'brand-instagram': InstagramIcon,
	'brand-youtube': YoutubeIcon,
	'brand-linkedin': LinkedinIcon,
	'brand-twitch': TwitchIcon,
	'brand-reddit': RedditIcon,
	'brand-bluesky': BlueskyIcon
} as const;

export type BuiltInIcon = keyof typeof iconDefinitions;
export type IconDefinition = (typeof iconDefinitions)[BuiltInIcon];